window.LAWYER_UP_DATA = {
  "crimes": [
    {
      "id": 1,
      "name": "Murder",
      "hostVal": 8
    },
    {
      "id": 2,
      "name": "Robbery",
      "hostVal": 5
    },
    {
      "id": 3,
      "name": "Causing Death by Driving",
      "hostVal": 3
    }
  ],
  "clients": [
    {
      "id": 2,
      "firstName": "Sam",
      "secondName": "Burtin",
      "country": "USA",
      "gender": "Male",
      "age": 21,
      "maritalStatus": "Single",
      "occupation": "Student",
      "crimeId": 2,
      "criminalHistory": "None",
      "hostVal": 6
    },
    {
      "id": 3,
      "firstName": "Mason",
      "secondName": "Bill",
      "country": "USA",
      "gender": "Male",
      "age": 54,
      "maritalStatus": "Married",
      "occupation": "Construction Worker",
      "crimeId": 2,
      "criminalHistory": "None",
      "hostVal": 3
    },
    {
      "id": 4,
      "firstName": "zn",
      "secondName": "jnj",
      "country": "nj",
      "gender": "jnjn",
      "age": 25,
      "maritalStatus": "mkmk",
      "occupation": "njn",
      "crimeId": 2,
      "criminalHistory": "njnj",
      "hostVal": 5
    },
    {
      "id": 5,
      "firstName": "Warren",
      "secondName": "Nolan",
      "country": "USA",
      "gender": "Male",
      "age": 25,
      "maritalStatus": "Single",
      "occupation": "real estate sales agent",
      "crimeId": 3,
      "criminalHistory": "None",
      "hostVal": 8
    },
    {
      "id": 6,
      "firstName": "Brenton",
      "secondName": "Bush",
      "country": "UK",
      "gender": "Male",
      "age": 27,
      "maritalStatus": "Married",
      "occupation": "power plant operator",
      "crimeId": 3,
      "criminalHistory": "None",
      "hostVal": 6
    },
    {
      "id": 7,
      "firstName": "Carlo",
      "secondName": "Schultz",
      "country": "USA",
      "gender": "Male",
      "age": 31,
      "maritalStatus": "Divorced",
      "occupation": "dental assistant",
      "crimeId": 1,
      "criminalHistory": "None",
      "hostVal": 5
    },
    {
      "id": 9,
      "firstName": "Aurelia",
      "secondName": "Houston",
      "country": "USA",
      "gender": "Female",
      "age": 35,
      "maritalStatus": "Married",
      "occupation": "gas compressor",
      "crimeId": 2,
      "criminalHistory": "None",
      "hostVal": 4
    },
    {
      "id": 13,
      "firstName": "Bo",
      "secondName": "Deleon",
      "country": "UK",
      "gender": "Male",
      "age": 53,
      "maritalStatus": "Divorced",
      "occupation": "gaming booth cashier",
      "crimeId": 3,
      "criminalHistory": "Yes",
      "hostVal": 7
    },
    {
      "id": 15,
      "firstName": "Renaldo",
      "secondName": "Olsen",
      "country": "USA",
      "gender": "Male",
      "age": 60,
      "maritalStatus": "Married",
      "occupation": "chef",
      "crimeId": 3,
      "criminalHistory": "None",
      "hostVal": 2
    },
    {
      "id": 16,
      "firstName": "Leif",
      "secondName": "Price",
      "country": "UK",
      "gender": "Male",
      "age": 64,
      "maritalStatus": "Divorced",
      "occupation": "advertising sales agent",
      "crimeId": 3,
      "criminalHistory": "None",
      "hostVal": 5
    },
    {
      "id": 17,
      "firstName": "Sue",
      "secondName": "Bray",
      "country": "USA",
      "gender": "Female",
      "age": 25,
      "maritalStatus": "Single",
      "occupation": "interior designer",
      "crimeId": 1,
      "criminalHistory": "None",
      "hostVal": 4
    },
    {
      "id": 18,
      "firstName": "Amalia",
      "secondName": "Holder",
      "country": "UK",
      "gender": "Female",
      "age": 27,
      "maritalStatus": "Married",
      "occupation": "nursing aide",
      "crimeId": 2,
      "criminalHistory": "None",
      "hostVal": 3
    },
    {
      "id": 19,
      "firstName": "Louisa",
      "secondName": "Savage",
      "country": "USA",
      "gender": "Female",
      "age": 31,
      "maritalStatus": "Married",
      "occupation": "aerobics instructor",
      "crimeId": 1,
      "criminalHistory": "None",
      "hostVal": 2
    },
    {
      "id": 20,
      "firstName": "Cody",
      "secondName": "Kane",
      "country": "Australia",
      "gender": "Male",
      "age": 33,
      "maritalStatus": "Divorced",
      "occupation": "firefighter",
      "crimeId": 3,
      "criminalHistory": "Yes",
      "hostVal": 7
    },
    {
      "id": 21,
      "firstName": "Jarrett",
      "secondName": "Leblanc",
      "country": "New Zealand",
      "gender": "Male",
      "age": 35,
      "maritalStatus": "Married",
      "occupation": "materials engineer",
      "crimeId": 1,
      "criminalHistory": "None",
      "hostVal": 4
    },
    {
      "id": 22,
      "firstName": "Logan",
      "secondName": "Drake",
      "country": "USA",
      "gender": "Male",
      "age": 40,
      "maritalStatus": "Single",
      "occupation": "social worker",
      "crimeId": 3,
      "criminalHistory": "None",
      "hostVal": 5
    },
    {
      "id": 23,
      "firstName": "Joann",
      "secondName": "Hanna",
      "country": "UK",
      "gender": "Male",
      "age": 45,
      "maritalStatus": "Married",
      "occupation": "crane operator",
      "crimeId": 2,
      "criminalHistory": "Yes",
      "hostVal": 6
    },
    {
      "id": 24,
      "firstName": "Johnathon",
      "secondName": "Horne",
      "country": "USA",
      "gender": "Male",
      "age": 50,
      "maritalStatus": "Married",
      "occupation": "locksmith",
      "crimeId": 2,
      "criminalHistory": "Yes",
      "hostVal": 6
    },
    {
      "id": 25,
      "firstName": "Rene",
      "secondName": "Raymond",
      "country": "USA",
      "gender": "Female",
      "age": 53,
      "maritalStatus": "Married",
      "occupation": "librarian",
      "crimeId": 1,
      "criminalHistory": "Yes",
      "hostVal": 3
    },
    {
      "id": 26,
      "firstName": "Corine",
      "secondName": "Yoder",
      "country": "UK",
      "gender": "Female",
      "age": 57,
      "maritalStatus": "Married",
      "occupation": "makeup artist",
      "crimeId": 1,
      "criminalHistory": "None",
      "hostVal": 1
    },
    {
      "id": 27,
      "firstName": "Zane",
      "secondName": "Dennis",
      "country": "USA",
      "gender": "Female",
      "age": 60,
      "maritalStatus": "Divorced",
      "occupation": "religious worker",
      "crimeId": 3,
      "criminalHistory": "None",
      "hostVal": 3
    },
    {
      "id": 29,
      "firstName": "Jefferson",
      "secondName": "Jennings",
      "country": "USA",
      "gender": "Male",
      "age": 23,
      "maritalStatus": "Married",
      "occupation": "animal breeder",
      "crimeId": 2,
      "criminalHistory": "None",
      "hostVal": 4
    },
    {
      "id": 30,
      "firstName": "Elisa",
      "secondName": "Boyd",
      "country": "Australia",
      "gender": "Female",
      "age": 19,
      "maritalStatus": "Divorced",
      "occupation": "library assistant",
      "crimeId": 2,
      "criminalHistory": "None",
      "hostVal": 3
    },
    {
      "id": 31,
      "firstName": "Margo",
      "secondName": "Soto",
      "country": "New Zealand",
      "gender": "Female",
      "age": 18,
      "maritalStatus": "Single",
      "occupation": "maid",
      "crimeId": 2,
      "criminalHistory": "Yes",
      "hostVal": 5
    },
    {
      "id": 33,
      "firstName": "Tabatha",
      "secondName": "Ross",
      "country": "UK",
      "gender": "Female",
      "age": 22,
      "maritalStatus": "Married",
      "occupation": "funeral director",
      "crimeId": 1,
      "criminalHistory": "None",
      "hostVal": 4
    },
    {
      "id": 34,
      "firstName": "Beulah",
      "secondName": "Randolph",
      "country": "USA",
      "gender": "Female",
      "age": 39,
      "maritalStatus": "Married",
      "occupation": "lobby attendant",
      "crimeId": 1,
      "criminalHistory": "Yes",
      "hostVal": 4
    },
    {
      "id": 35,
      "firstName": "Phillip",
      "secondName": "Mendez",
      "country": "USA",
      "gender": "Male",
      "age": 24,
      "maritalStatus": "Married",
      "occupation": "fitness trainer",
      "crimeId": 1,
      "criminalHistory": "None",
      "hostVal": 5
    },
    {
      "id": 36,
      "firstName": "Denny",
      "secondName": "Conway",
      "country": "UK",
      "gender": "Male",
      "age": 41,
      "maritalStatus": "Single",
      "occupation": "insulation worker",
      "crimeId": 3,
      "criminalHistory": "None",
      "hostVal": 4
    },
    {
      "id": 38,
      "firstName": "Esmeralda",
      "secondName": "Richards",
      "country": "UK",
      "gender": "Female",
      "age": 21,
      "maritalStatus": "Married",
      "occupation": "human resources assistant",
      "crimeId": 2,
      "criminalHistory": "Yes",
      "hostVal": 4
    },
    {
      "id": 39,
      "firstName": "Mary",
      "secondName": "Salazar",
      "country": "USA",
      "gender": "Female",
      "age": 22,
      "maritalStatus": "Married",
      "occupation": "communications teacher",
      "crimeId": 2,
      "criminalHistory": "None",
      "hostVal": 2
    },
    {
      "id": 40,
      "firstName": "Lela",
      "secondName": "Doyle",
      "country": "Australia",
      "gender": "Female",
      "age": 23,
      "maritalStatus": "Single",
      "occupation": "attendant",
      "crimeId": 2,
      "criminalHistory": "None",
      "hostVal": 4
    },
    {
      "id": 42,
      "firstName": "Pamela",
      "secondName": "Andrews",
      "country": "USA",
      "gender": "Female",
      "age": 25,
      "maritalStatus": "Single",
      "occupation": "foreign literature teacher",
      "crimeId": 1,
      "criminalHistory": "None",
      "hostVal": 4
    },
    {
      "id": 43,
      "firstName": "Gil",
      "secondName": "Jones",
      "country": "UK",
      "gender": "Male",
      "age": 23,
      "maritalStatus": "Married",
      "occupation": "travel guide",
      "crimeId": 2,
      "criminalHistory": "None",
      "hostVal": 4
    },
    {
      "id": 44,
      "firstName": "Sonya",
      "secondName": "Stewart",
      "country": "USA",
      "gender": "Female",
      "age": 19,
      "maritalStatus": "Single",
      "occupation": "music teacher",
      "crimeId": 2,
      "criminalHistory": "Yes",
      "hostVal": 5
    },
    {
      "id": 45,
      "firstName": "Clare",
      "secondName": "Roth",
      "country": "USA",
      "gender": "Female",
      "age": 18,
      "maritalStatus": "Single",
      "occupation": "waitress",
      "crimeId": 2,
      "criminalHistory": "None",
      "hostVal": 4
    },
    {
      "id": 46,
      "firstName": "Sheri",
      "secondName": "Reynolds",
      "country": "UK",
      "gender": "Female",
      "age": 19,
      "maritalStatus": "Single",
      "occupation": "interviewer",
      "crimeId": 2,
      "criminalHistory": "None",
      "hostVal": 4
    },
    {
      "id": 48,
      "firstName": "Felicia",
      "secondName": "Wilkerson",
      "country": "UK",
      "gender": "Female",
      "age": 39,
      "maritalStatus": "Single",
      "occupation": "fabric patternmaker",
      "crimeId": 1,
      "criminalHistory": "None",
      "hostVal": 4
    },
    {
      "id": 49,
      "firstName": "Josef",
      "secondName": "Bates",
      "country": "USA",
      "gender": "Male",
      "age": 24,
      "maritalStatus": "Single",
      "occupation": "school bus driver",
      "crimeId": 3,
      "criminalHistory": "None",
      "hostVal": 6
    },
    {
      "id": 50,
      "firstName": "Etta",
      "secondName": "Black",
      "country": "Australia",
      "gender": "Female",
      "age": 41,
      "maritalStatus": "Married",
      "occupation": "manicurist",
      "crimeId": 2,
      "criminalHistory": "None",
      "hostVal": 1
    },
    {
      "id": 52,
      "firstName": "Myron",
      "secondName": "Rodgers",
      "country": "USA",
      "gender": "Male",
      "age": 21,
      "maritalStatus": "Single",
      "occupation": "tractor operator",
      "crimeId": 3,
      "criminalHistory": "Yes",
      "hostVal": 8
    },
    {
      "id": 55,
      "firstName": "Marty",
      "secondName": "Ross",
      "country": "USA",
      "gender": "Male",
      "age": 25,
      "maritalStatus": "Divorced",
      "occupation": "fundraising manager",
      "crimeId": 3,
      "criminalHistory": "Yes",
      "hostVal": 7
    },
    {
      "id": 56,
      "firstName": "Tomas",
      "secondName": "Andersen",
      "country": "UK",
      "gender": "Male",
      "age": 25,
      "maritalStatus": "Married",
      "occupation": "tree trimmer",
      "crimeId": 1,
      "criminalHistory": "Yes",
      "hostVal": 8
    },
    {
      "id": 57,
      "firstName": "Wilford",
      "secondName": "Tyler",
      "country": "USA",
      "gender": "Male",
      "age": 64,
      "maritalStatus": "Single",
      "occupation": "oral surgeon",
      "crimeId": 1,
      "criminalHistory": "None",
      "hostVal": 4
    },
    {
      "id": 61,
      "firstName": "Louie",
      "secondName": "Holden",
      "country": "New Zealand",
      "gender": "Male",
      "age": 33,
      "maritalStatus": "Married",
      "occupation": "camera operator",
      "crimeId": 1,
      "criminalHistory": "None",
      "hostVal": 4
    },
    {
      "id": 62,
      "firstName": "Emmett",
      "secondName": "Rivas",
      "country": "USA",
      "gender": "Male",
      "age": 35,
      "maritalStatus": "Married",
      "occupation": "hairdresser",
      "crimeId": 2,
      "criminalHistory": "Yes",
      "hostVal": 6
    },
    {
      "id": 64,
      "firstName": "Virgil",
      "secondName": "Rodriguez",
      "country": "USA",
      "gender": "Male",
      "age": 45,
      "maritalStatus": "Married",
      "occupation": "carpenter",
      "crimeId": 3,
      "criminalHistory": "None",
      "hostVal": 3
    },
    {
      "id": 65,
      "firstName": "Berry",
      "secondName": "Owens",
      "country": "USA",
      "gender": "Female",
      "age": 21,
      "maritalStatus": "Divorced",
      "occupation": "animal trainer",
      "crimeId": 2,
      "criminalHistory": "Yes",
      "hostVal": 5
    },
    {
      "id": 66,
      "firstName": "Oswaldo",
      "secondName": "Golden",
      "country": "UK",
      "gender": "Male",
      "age": 22,
      "maritalStatus": "Married",
      "occupation": "dishwasher",
      "crimeId": 2,
      "criminalHistory": "Yes",
      "hostVal": 6
    },
    {
      "id": 68,
      "firstName": "Nestor",
      "secondName": "Mays",
      "country": "UK",
      "gender": "Male",
      "age": 25,
      "maritalStatus": "Married",
      "occupation": "chauffeur",
      "crimeId": 1,
      "criminalHistory": "None",
      "hostVal": 5
    },
    {
      "id": 69,
      "firstName": "Ward",
      "secondName": "Hanna",
      "country": "USA",
      "gender": "Male",
      "age": 25,
      "maritalStatus": "Married",
      "occupation": "pesticide handler",
      "crimeId": 1,
      "criminalHistory": "None",
      "hostVal": 5
    },
    {
      "id": 70,
      "firstName": "Jan",
      "secondName": "Lin",
      "country": "Australia",
      "gender": "Female",
      "age": 64,
      "maritalStatus": "Married",
      "occupation": "archeologist",
      "crimeId": 1,
      "criminalHistory": "None",
      "hostVal": 1
    },
    {
      "id": 71,
      "firstName": "Ruby",
      "secondName": "Strickland",
      "country": "New Zealand",
      "gender": "Female",
      "age": 25,
      "maritalStatus": "Married",
      "occupation": "architect",
      "crimeId": 1,
      "criminalHistory": "None",
      "hostVal": 3
    },
    {
      "id": 72,
      "firstName": "Israel",
      "secondName": "Velazquez",
      "country": "USA",
      "gender": "Female",
      "age": 27,
      "maritalStatus": "Married",
      "occupation": "dancer",
      "crimeId": 1,
      "criminalHistory": "None",
      "hostVal": 3
    },
    {
      "id": 73,
      "firstName": "Adeline",
      "secondName": "Forbes",
      "country": "UK",
      "gender": "Female",
      "age": 31,
      "maritalStatus": "Single",
      "occupation": "jeweler",
      "crimeId": 1,
      "criminalHistory": "Yes",
      "hostVal": 7
    },
    {
      "id": 74,
      "firstName": "Caitlin",
      "secondName": "Doyle",
      "country": "USA",
      "gender": "Female",
      "age": 33,
      "maritalStatus": "Married",
      "occupation": "paralegal",
      "crimeId": 1,
      "criminalHistory": "None",
      "hostVal": 3
    },
    {
      "id": 77,
      "firstName": "Harold",
      "secondName": "Baker",
      "country": "USA",
      "gender": "Male",
      "age": 31,
      "maritalStatus": "Married",
      "occupation": "fine artist",
      "crimeId": 1,
      "criminalHistory": "None",
      "hostVal": 4
    },
    {
      "id": 78,
      "firstName": "Buster",
      "secondName": "Sheppard",
      "country": "UK",
      "gender": "Male",
      "age": 33,
      "maritalStatus": "Married",
      "occupation": "bartender",
      "crimeId": 3,
      "criminalHistory": "None",
      "hostVal": 6
    },
    {
      "id": 79,
      "firstName": "Mohammad",
      "secondName": "Bridges",
      "country": "USA",
      "gender": "Male",
      "age": 35,
      "maritalStatus": "Married",
      "occupation": "security guard",
      "crimeId": 1,
      "criminalHistory": "None",
      "hostVal": 5
    },
    {
      "id": 82,
      "firstName": "Andres",
      "secondName": "Park",
      "country": "USA",
      "gender": "Male",
      "age": 50,
      "maritalStatus": "Married",
      "occupation": "priest",
      "crimeId": 3,
      "criminalHistory": "None",
      "hostVal": 4
    },
    {
      "id": 83,
      "firstName": "Odis",
      "secondName": "Warner",
      "country": "UK",
      "gender": "Female",
      "age": 53,
      "maritalStatus": "Married",
      "occupation": "illustrator",
      "crimeId": 1,
      "criminalHistory": "None",
      "hostVal": 1
    },
    {
      "id": 84,
      "firstName": "Danilo",
      "secondName": "Cochran",
      "country": "USA",
      "gender": "Male",
      "age": 57,
      "maritalStatus": "Divorced",
      "occupation": "religious worker",
      "crimeId": 2,
      "criminalHistory": "None",
      "hostVal": 5
    },
    {
      "id": 85,
      "firstName": "Maribel",
      "secondName": "Cunningham",
      "country": "USA",
      "gender": "Male",
      "age": 60,
      "maritalStatus": "Single",
      "occupation": "property manager",
      "crimeId": 3,
      "criminalHistory": "None",
      "hostVal": 6
    },
    {
      "id": 86,
      "firstName": "Ronny",
      "secondName": "Roberts",
      "country": "UK",
      "gender": "Male",
      "age": 64,
      "maritalStatus": "Married",
      "occupation": "personal chef",
      "crimeId": 2,
      "criminalHistory": "Yes",
      "hostVal": 4
    },
    {
      "id": 88,
      "firstName": "Leila",
      "secondName": "Larsen",
      "country": "UK",
      "gender": "Female",
      "age": 27,
      "maritalStatus": "Married",
      "occupation": "bartender",
      "crimeId": 2,
      "criminalHistory": "None",
      "hostVal": 4
    },
    {
      "id": 90,
      "firstName": "Noelle",
      "secondName": "Figueroa",
      "country": "Australia",
      "gender": "Male",
      "age": 33,
      "maritalStatus": "Married",
      "occupation": "civil engineering technician",
      "crimeId": 3,
      "criminalHistory": "Yes",
      "hostVal": 6
    },
    {
      "id": 92,
      "firstName": "Jewel",
      "secondName": "Wells",
      "country": "USA",
      "gender": "Male",
      "age": 40,
      "maritalStatus": "Married",
      "occupation": "tailor",
      "crimeId": 3,
      "criminalHistory": "None",
      "hostVal": 2
    },
    {
      "id": 93,
      "firstName": "Alison",
      "secondName": "Camacho",
      "country": "UK",
      "gender": "Female",
      "age": 45,
      "maritalStatus": "Married",
      "occupation": "hotel desk clerk",
      "crimeId": 2,
      "criminalHistory": "None",
      "hostVal": 1
    },
    {
      "id": 94,
      "firstName": "Kathryn",
      "secondName": "Lynch",
      "country": "USA",
      "gender": "Female",
      "age": 50,
      "maritalStatus": "Married",
      "occupation": "textile presser",
      "crimeId": 1,
      "criminalHistory": "None",
      "hostVal": 1
    },
    {
      "id": 97,
      "firstName": "Tabitha",
      "secondName": "Mueller",
      "country": "USA",
      "gender": "Female",
      "age": 60,
      "maritalStatus": "Single",
      "occupation": "kindergarten teacher",
      "crimeId": 3,
      "criminalHistory": "Yes",
      "hostVal": 4
    },
    {
      "id": 100,
      "firstName": "Edith",
      "secondName": "Phelps",
      "country": "Australia",
      "gender": "Male",
      "age": 19,
      "maritalStatus": "Single",
      "occupation": "electrician",
      "crimeId": 2,
      "criminalHistory": "Yes",
      "hostVal": 7
    },
    {
      "id": 103,
      "firstName": "Gale",
      "secondName": "Barton",
      "country": "UK",
      "gender": "Male",
      "age": 22,
      "maritalStatus": "Single",
      "occupation": "cook",
      "crimeId": 2,
      "criminalHistory": "None",
      "hostVal": 6
    },
    {
      "id": 104,
      "firstName": "Reva",
      "secondName": "Wilkinson",
      "country": "USA",
      "gender": "Male",
      "age": 39,
      "maritalStatus": "Single",
      "occupation": "taxi driver",
      "crimeId": 3,
      "criminalHistory": "None",
      "hostVal": 6
    }
  ],
  "questions": [
    {
      "id": 1,
      "crimeId": 1,
      "question": "What age-bracket does the victim belong to?",
      "questionNo": 1,
      "option1": "0-25yrs",
      "option2": "25-60yrs",
      "option3": "60-100yrs",
      "hostVal1": 9,
      "hostVal2": 6,
      "hostVal3": 4
    },
    {
      "id": 10,
      "crimeId": 1,
      "question": "What is the financial status of the victim?",
      "questionNo": 2,
      "option1": "Poor",
      "option2": "Middle-class",
      "option3": "Very wealthy",
      "hostVal1": 6,
      "hostVal2": 8,
      "hostVal3": 10
    },
    {
      "id": 7,
      "crimeId": 1,
      "question": "How many dependents does the client have?",
      "questionNo": 3,
      "option1": "0-1",
      "option2": "2-4",
      "option3": ">4",
      "hostVal1": 10,
      "hostVal2": 7,
      "hostVal3": 4
    },
    {
      "id": 6,
      "crimeId": 1,
      "question": "How stable is the client's mental health?",
      "questionNo": 4,
      "option1": "The client is a highly functioning induvidual and does not require any mental health attention",
      "option2": "The client is a poorly functioning induvidual and may require some mental health attention",
      "option3": "The client is a non-functioning induvidual and has been diagnosed with several mental issues",
      "hostVal1": 10,
      "hostVal2": 6,
      "hostVal3": 4
    },
    {
      "id": 9,
      "crimeId": 1,
      "question": "Is there a witness when the crime happened?",
      "questionNo": 5,
      "option1": "Yes",
      "option2": "No but there is a camera recording that captured the act being carried out by client",
      "option3": "No,there were no witnesses but there is evidence that strongly suggests that the client  attended the victims place just a few hours before the act was reported to police",
      "hostVal1": 8,
      "hostVal2": 10,
      "hostVal3": 5
    },
    {
      "id": 8,
      "crimeId": 1,
      "question": "Is the client the sole member responsible for his actions?",
      "questionNo": 6,
      "option1": "Yes",
      "option2": "No, it was organised by a group of friends ",
      "option3": "No, the client merely executed the act concieved by a third-party for monetary incentive",
      "hostVal1": 10,
      "hostVal2": 8,
      "hostVal3": 9
    },
    {
      "id": 3,
      "crimeId": 1,
      "question": "What was the motive behind the murder?",
      "questionNo": 7,
      "option1": "The Client claims to be cheated by the Victim before",
      "option2": "The client claims that it was an accident that happened as self-defense",
      "option3": "The client claims to have been publicly humiliated by the victim before",
      "hostVal1": 8,
      "hostVal2": 6,
      "hostVal3": 10
    },
    {
      "id": 4,
      "crimeId": 1,
      "question": "When did the client start contemplating about commiting this crime?",
      "questionNo": 8,
      "option1": "Between 1-2 hrs from when the action happened",
      "option2": "Between 1-6 days from when the action happened",
      "option3": "More than 7 days from when the action happened",
      "hostVal1": 6,
      "hostVal2": 8,
      "hostVal3": 10
    },
    {
      "id": 2,
      "crimeId": 1,
      "question": "What is the weapon used to carry out the murder?",
      "questionNo": 9,
      "option1": "Knife",
      "option2": "Gun",
      "option3": "Poison",
      "hostVal1": 4,
      "hostVal2": 8,
      "hostVal3": 6
    },
    {
      "id": 5,
      "crimeId": 1,
      "question": "Does the client plead guilty?",
      "questionNo": 10,
      "option1": "The client will plead guilty immediately",
      "option2": "The client will plead guilty eventually",
      "option3": "The client refuses to plead guilty",
      "hostVal1": 4,
      "hostVal2": 7,
      "hostVal3": 10
    },
    {
      "id": 11,
      "crimeId": 2,
      "question": "What is the level of usage of the arms found with the client?",
      "questionNo": 1,
      "option1": "The client has used the weapon to threaten the victim",
      "option2": "The client has used the weapon to inflict harm on the victim as the victim resisted the act",
      "option3": "The client has used the weapon as a tool to break the doors and windows ",
      "hostVal1": 8,
      "hostVal2": 10,
      "hostVal3": 5
    },
    {
      "id": 12,
      "crimeId": 2,
      "question": "What were the extent of injuries found at the incident due to the course of robbery?",
      "questionNo": 2,
      "option1": "Minimal physical or psychological harm caused to the victim",
      "option2": "Serious physical and/or psychological harm caused to the victim",
      "option3": "Serious detrimental effect on the property",
      "hostVal1": 4,
      "hostVal2": 10,
      "hostVal3": 8
    },
    {
      "id": 13,
      "crimeId": 2,
      "question": "What is the value of the goods stolen?",
      "questionNo": 3,
      "option1": "Under 250K USD",
      "option2": "Between 250K-750K USD",
      "option3": "Over 1M USD",
      "hostVal1": 2,
      "hostVal2": 6,
      "hostVal3": 10
    },
    {
      "id": 14,
      "crimeId": 2,
      "question": "When did the client start contemplating about commiting this crime?",
      "questionNo": 4,
      "option1": "Over a month ago",
      "option2": "15 days ago",
      "option3": "5 days ago",
      "hostVal1": 10,
      "hostVal2": 6,
      "hostVal3": 3
    },
    {
      "id": 15,
      "crimeId": 2,
      "question": "Was the client under the influence of alcohol/drugs during the act?",
      "questionNo": 5,
      "option1": "Yes, the client consmed alcohol an hour before commitimg the crime",
      "option2": "Yes, the client consumed Cocaine at the location of crime",
      "option3": "No, the client wanted everything to go according to his plan as he wanted it to",
      "hostVal1": 8,
      "hostVal2": 10,
      "hostVal3": 3
    },
    {
      "id": 16,
      "crimeId": 2,
      "question": "Is the client the sole member responsible for this crime?",
      "questionNo": 6,
      "option1": "Yes",
      "option2": "No, it was organised by a group of friends but the client led the team through the act",
      "option3": "No, it was organised by a group of friends and the client merely followed his orders",
      "hostVal1": 10,
      "hostVal2": 8,
      "hostVal3": 5
    },
    {
      "id": 17,
      "crimeId": 2,
      "question": "How many dependents does the client have?",
      "questionNo": 7,
      "option1": "0-1",
      "option2": "2-4",
      "option3": ">4",
      "hostVal1": 10,
      "hostVal2": 7,
      "hostVal3": 4
    },
    {
      "id": 18,
      "crimeId": 2,
      "question": "Does the client plead guilty of his actions?",
      "questionNo": 8,
      "option1": "The client will plead guilty immediately",
      "option2": "The client will plead guilty eventually",
      "option3": "The client refuses to plead guilty",
      "hostVal1": 2,
      "hostVal2": 6,
      "hostVal3": 10
    },
    {
      "id": 19,
      "crimeId": 2,
      "question": "How stable is the client's mental health?",
      "questionNo": 9,
      "option1": "The client is a highly functioning induvidual and does not require any mental health attention",
      "option2": "The client is a poorly functioning induvidual and may require some mental health attention",
      "option3": "The client is a non-functioning induvidual and has been diagnosed with several mental issues",
      "hostVal1": 10,
      "hostVal2": 6,
      "hostVal3": 2
    },
    {
      "id": 20,
      "crimeId": 2,
      "question": "Who were present from the victims end at the location during the crime?",
      "questionNo": 10,
      "option1": "Victim, spouse, children",
      "option2": "Victim, Spouse, Parents",
      "option3": "Victim was alone",
      "hostVal1": 10,
      "hostVal2": 7,
      "hostVal3": 5
    },
    {
      "id": 21,
      "crimeId": 3,
      "question": "Is the client under the influence of alcohol or drugs while driving?",
      "questionNo": 1,
      "option1": "Yes, the client consmed alcohol an hour before driving",
      "option2": "Yes, the client consumed Cocaine at the location of crime",
      "option3": "No, the client did not consume any alcohol or drugs",
      "hostVal1": 8,
      "hostVal2": 10,
      "hostVal3": 2
    },
    {
      "id": 22,
      "crimeId": 3,
      "question": "Is the client an unlisenced, uninsured or disqualified driver?",
      "questionNo": 2,
      "option1": "Yes, the client is unlicensed and uninsured",
      "option2": "Yes, the client was disqualified from driving before",
      "option3": "No, the client has proper license and insurance",
      "hostVal1": 7,
      "hostVal2": 10,
      "hostVal3": 5
    },
    {
      "id": 23,
      "crimeId": 3,
      "question": "How many people were injured or killed as a result of the offence?",
      "questionNo": 3,
      "option1": "2 Killed,1 injured",
      "option2": "1 killed,3 injured",
      "option3": "3 killed, 0 injured",
      "hostVal1": 8,
      "hostVal2": 4,
      "hostVal3": 10
    },
    {
      "id": 24,
      "crimeId": 3,
      "question": "Was the client injured as a result of the offence?",
      "questionNo": 4,
      "option1": "Yes, the client sufferred severe injuries to neck and back",
      "option2": "Yes, the client suffered from minor injuries to hands and legs",
      "option3": "No, the client was not injured",
      "hostVal1": 2,
      "hostVal2": 6,
      "hostVal3": 10
    },
    {
      "id": 25,
      "crimeId": 3,
      "question": "Were any of the injured victims a close friend or relative of the client?",
      "questionNo": 5,
      "option1": "Yes, all of them were the friends of client",
      "option2": "Yes, one of the client's relatives was killed as a result of the offence",
      "option3": "No, all of them were strangers to client",
      "hostVal1": 4,
      "hostVal2": 7,
      "hostVal3": 10
    },
    {
      "id": 26,
      "crimeId": 3,
      "question": "Where did the accident haapen ?",
      "questionNo": 6,
      "option1": "Isolated area with low traffic",
      "option2": "Busy area with high traffic",
      "option3": "Normal Area with normal traffic",
      "hostVal1": 10,
      "hostVal2": 5,
      "hostVal3": 6
    },
    {
      "id": 27,
      "crimeId": 3,
      "question": "Were any of the victims working for the Public sector? ",
      "questionNo": 7,
      "option1": "No",
      "option2": "Yes, all of them were working in public sector",
      "option3": "Yes, one of the victims was working in public sector",
      "hostVal1": 2,
      "hostVal2": 10,
      "hostVal3": 8
    },
    {
      "id": 28,
      "crimeId": 3,
      "question": "Was the client violating any traffic laws?",
      "questionNo": 8,
      "option1": "Yes, the client was texting and driving",
      "option2": "Yes, the client was speeding over the limit",
      "option3": "Yes, the client was speeding and not obeying the traffic signals ",
      "hostVal1": 5,
      "hostVal2": 8,
      "hostVal3": 10
    },
    {
      "id": 29,
      "crimeId": 3,
      "question": "What did the client do as soon as the accident occurred?",
      "questionNo": 9,
      "option1": "The client was shocked and drove away",
      "option2": "The client called the ambulance and drove away",
      "option3": "The client called the ambulance,later informed the cops and turned himself in",
      "hostVal1": 10,
      "hostVal2": 4,
      "hostVal3": 2
    },
    {
      "id": 30,
      "crimeId": 3,
      "question": "Does the client plead guilty of his actions?",
      "questionNo": 10,
      "option1": "The client will plead guilty immediately",
      "option2": "The client will plead guilty eventually",
      "option3": "The client refuses to plead guilty",
      "hostVal1": 2,
      "hostVal2": 6,
      "hostVal3": 10
    }
  ]
};
